RoadSafety/Models/Master_Accident.cs
using System.ComponentModel.DataAnnotations;

namespace RoadSafety.Models
{
    public class Master_Accident
    {
        public int?     AccidentID      { get; set; }

        
        public int      Vehicle1ID      { get; set; }

      
        public int      Vehicle2ID      { get; set; }


        public int      CountryID      { get; set; }
        public int StateID { get; set; }

        public int CityID { get; set; }

        public DateTime Date            { get; set; }
        public int      Casuality       { get; set; }
        public int      Death       { get; set; }
        public object Casulity { get; internal set; }
    }
}

RoadSafety/Controllers/Master_AccidentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using RoadSafety.Models;

namespace RoadSafety.Controllers
{
    public class Master_AccidentController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public Master_AccidentController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        #endregion
        #region Delete
        public IActionResult Delete(int AccidentID)
        {
            DataTable dt = new DataTable();
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Master_Accident_DeleteByPK";
            cmd.Parameters.AddWithValue("@AccidentID", AccidentID);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
        #endregion
        public IActionResult Index()
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);

            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Master_Accident_SelectAll";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);

            return View("Master_AccidentList", dt);

            conn.Close();
        }


        #region DropDownByCountry
        public IActionResult DropDownByCountry(int CountryID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn1 = new SqlConnection(str);
            DataTable dt1 = new DataTable();
            conn1.Open();
            SqlCommand cmd1 = conn1.CreateCommand();
            cmd1.CommandType = CommandType.StoredProcedure;
            cmd1.CommandText = "PR_LOC_State_SelectDropDownByCountryID";
            cmd1.Parameters.AddWithValue("@CountryID", CountryID);
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);


            List<LOC_StateDropDownModel> state_list = new List<LOC_StateDropDownModel>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                LOC_StateDropDownModel vlst1 = new LOC_StateDropDownModel();
                vlst1.StateID = Convert.ToInt32(dr1["StateID"]);
                vlst1.StateName = dr1["StateName"].ToString();
                state_list.Add(vlst1);
            }
            ViewBag.StateList = state_list;
            var vModel = state_list;
            return Json(vModel);
            conn1.Close();

            
        }
        #endregion
        
        
        #region DropDownByState
        public IActionResult DropDownByState(int StateID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn2 = new SqlConnection(str);
            DataTable dt2 = new DataTable();
            conn2.Open();
            SqlCommand cmd1 = conn2.CreateCommand();
            cmd1.CommandType = CommandType.StoredProcedure;
            cmd1.CommandText = "PR_LOC_City_SelectDropDownByStateID";
            cmd1.Parameters.AddWithValue("@StateID", StateID);
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt2.Load(sdr1);


            List<LOC_CityDropDownModel> list3 = new List<LOC_CityDropDownModel>();
            foreach (DataRow dr2 in dt2.Rows)
            {
                LOC_CityDropDownModel vlst1 = new LOC_CityDropDownModel();
                vlst1.CityID = Convert.ToInt32(dr2["CityID"]);
                vlst1.CityName = dr2["CityName"].ToString();
                list3.Add(vlst1);
            }
            ViewBag.CityList = list3;
            var vModel = list3;
            conn2.Close();
            return Json(vModel);
            #endregion
        }
        #region Save
        [HttpPost]
        public IActionResult Save(Master_Accident modelMaster_Accident)
        {


            //if (ModelState.IsValid)
            //{
            #region Insert

            String str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;

            if (modelMaster_Accident.AccidentID == null)
            {
                cmd.CommandText = "PR_Master_Accident_Insert";
                
            }
            #endregion

            #region UpdateByPk
            else
            {
                cmd.CommandText = "PR_Master_Accident_UpdateByPK";
                cmd.Parameters.Add("@AccidentID", SqlDbType.Int).Value = modelMaster_Accident.AccidentID;
            }
            #endregion

            cmd.Parameters.Add("@Vehicle1ID", SqlDbType.Int).Value = modelMaster_Accident.Vehicle1ID;
            cmd.Parameters.Add("@Vehicle2ID", SqlDbType.Int).Value = modelMaster_Accident.Vehicle2ID;
            cmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelMaster_Accident.CountryID;
            cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = modelMaster_Accident.StateID;
            cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = modelMaster_Accident.CityID;
            cmd.Parameters.Add("@Casuality", SqlDbType.Int).Value = modelMaster_Accident.Casuality;
            cmd.Parameters.Add("@Death", SqlDbType.Int).Value = modelMaster_Accident.Death;
            cmd.Parameters.Add("@Date", SqlDbType.Date).Value = modelMaster_Accident.Date;


            if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
            {
                if (modelMaster_Accident.AccidentID == null)
                    TempData["ContactInsertMsg"] = "Record Inserted Sucessfully!!";
                else
                    TempData["ContactInsertMsg"] = "Record Updated Sucessfully!!";
            }
            conn.Close();

            return RedirectToAction("Index");
        }
        #endregion
        #region Add
        public IActionResult Add(int? AccidentID)
        {
            #region Select for  Dropdown vehicle1
            string str1 = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn1 = new SqlConnection(str1);
            conn1.Open();
            SqlCommand cmd1 = conn1.CreateCommand();
            cmd1.CommandType = CommandType.StoredProcedure;
            cmd1.CommandText = "PR_VEH_Vehicle1_SelectForDropDown";

            DataTable dt1 = new DataTable();
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);

            List<VEH_Vehicle1DropDownModel> List = new List<VEH_Vehicle1DropDownModel>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                VEH_Vehicle1DropDownModel vlst = new VEH_Vehicle1DropDownModel();
                vlst.Vehicle1ID = Convert.ToInt32(dr1["Vehicle1ID"]);
                vlst.Vehicle1Type = dr1["Vehicle1Type"].ToString();
                List.Add(vlst);
            }
            ViewBag.Vehicle1List = List;
            conn1.Close();
            #endregion

            #region Select for  Dropdown vehicle2
            string str5 = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn5 = new SqlConnection(str5);
            conn5.Open();
            SqlCommand cmd5 = conn5.CreateCommand();
            cmd5.CommandType = CommandType.StoredProcedure;
            cmd5.CommandText = "PR_VEH_Vehicle2_SelectForDropDown";

            DataTable dt5 = new DataTable();
            SqlDataReader sdr5 = cmd5.ExecuteReader();
            dt5.Load(sdr5);

            List<VEH_Vehicle2DropDownModel> List5 = new List<VEH_Vehicle2DropDownModel>();
            foreach (DataRow dr5 in dt5.Rows)
            {
                VEH_Vehicle2DropDownModel vlst5 = new VEH_Vehicle2DropDownModel();
                vlst5.Vehicle2ID = Convert.ToInt32(dr5["Vehicle2ID"]);
                vlst5.Vehicle2Type = dr5["Vehicle2Type"].ToString();
                List5.Add(vlst5);
            }
            ViewBag.Vehicle2List = List5;
            #endregion

            #region Country Drop Down

            SqlConnection conn2 = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));

            conn2.Open();

            SqlCommand Cmd1 = conn2.CreateCommand();
            Cmd1.CommandType = CommandType.StoredProcedure;
            Cmd1.CommandText = "PR_LOC_Country_SelectForDropDown";
            SqlDataReader objSDR1 = Cmd1.ExecuteReader();
            DataTable dt2 = new DataTable();
            dt2.Load(objSDR1);

            List<LOC_CountryDropDownModel> list = new List<LOC_CountryDropDownModel>();
            foreach (DataRow dr in dt2.Rows)
            {
                LOC_CountryDropDownModel vlst = new LOC_CountryDropDownModel();
                vlst.CountryID = Convert.ToInt32(@dr["CountryID"]);
                vlst.CountryName = dr["CountryName"].ToString();
                list.Add(vlst);
            }
            ViewBag.CountryList = list;
            conn2.Close();
            #endregion

            #region State Drop Down

       
            List<LOC_StateDropDownModel> state_list = new List<LOC_StateDropDownModel>();
          
            ViewBag.StateList = state_list;
            
            #endregion

            #region City Drop Down
            
            List<LOC_CityDropDownModel> list3 = new List<LOC_CityDropDownModel>();
           
            ViewBag.CityList = list3;
           
            #endregion

            

            if (AccidentID != null)
            {

RoadSafety/Views/Master_Accident/Master_AccidentAddEdit.cshtml
@{
    ViewData["Title"] = "AddCity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Master_Accident


<div class="responsive">
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE TITLE-->
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->

            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="row">
                        <div class="caption font-green-haze col-md-10">
                            <i class="icon-plus font-green"></i>
                            <span class="caption-subject bold uppercase"> Add Country</span>
                        </div>
                        <div class="caption font-green-haze" style="float:right">
                            <a class="btn btn-success" asp-action="Index">Back to List</a>
                        </div>
                    </div>


                </div>

                <div class="portlet-body form">

                    <div class="row">
                        <div class="col-md-12" style="font-family:'Bahnschrift';font-size:large">
                            <h3>@TempData["ContactInsertMsg"]</h3>
                            <h3>@TempData["ContactUpdateMsg"]</h3>
                            <form method="post" asp-controller="Master_Accident" asp-action="Save" enctype="multipart/form-data">
                                @Html.HiddenFor(x=>x.AccidentID)
                                <div class="form-group">
                                    <label>Vehicle Name :</label>
                                    @*<input type="text" class="form-control" asp-for="Vehicle1ID" asp-items="@(new SelectList(ViewBag.Vehicle1List,"Vehicle1ID","VehicleType"))" placeholder="Enter Vehicle Type" />*@
                                    <select class="form-control" asp-for="Vehicle1ID" asp-items="@(new SelectList(ViewBag.Vehicle1List,"Vehicle1ID","Vehicle1Type"))">
                                    <option value="">Select Vehicle</option>
                                </select>
                                    <span asp-validation-for="Vehicle1ID" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Vehicle Name :</label>
                                    @*<input type="text" class="form-control" asp-for="Vehicle2ID" placeholder="Enter Vehicle Code" />*@
                                    <select class="form-control" asp-for="Vehicle2ID" asp-items="@(new SelectList(ViewBag.Vehicle2List,"Vehicle2ID","Vehicle2Type"))">
                                        <option value="">Select Vehicle</option>
                                    </select>
                                    <span asp-validation-for="Vehicle2ID" class="text-danger"></span>
                                </div>
                                @*<div class="form-group">
                                <label>Upload File</label>
                                <input type="file" asp-for="File" placeholder="Upload your file" class="form-control" />
                                </div>*@
                                <div class="form-group">
                                    <label>Country Name : </label>
                                    @*<input type="text" class="form-control" asp-for="CountryID" placeholder="Enter Country ID" />*@
                                    <select class="form-control" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" onchange="fnOnCountryChange();">
                                        <option value="">Select Country</option>
                                    </select>
                                    <span asp-validation-for="CountryID" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>State Name : </label>
                                    @*<input type="text" class="form-control" asp-for="StateID" placeholder="Enter State ID" />*@
                                    <select class="form-control" asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))" onchange="fnOnStateChange();">
                                        <option value="">Select State</option>
                                    </select>
                                    <span asp-validation-for="StateID" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>City Name : </label>
                                    @*<input type="text" class="form-control" asp-for="CityID" placeholder="Enter City ID" />*@
                                    <select asp-for="CityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID","CityName"))" class="form-control">
                                        <option value="">Select City</option>
                                    </select>
                                    <span asp-validation-for="CityID" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Date : </label>
                                    <input type="date" class="form-control" asp-for="Date" />
                                </div>
                                <div class="form-group">
                                    <label>Injured : </label>
                                    <input type="text" class="form-control" asp-for="Casuality" placeholder="Enter Injured " />
                                    <span asp-validation-for="Casuality" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Death : </label>
                                    <input type="text" class="form-control" asp-for="Death" placeholder="Enter Death " />
                                    <span asp-validation-for="Death" class="text-danger"></span>
                                </div>
                                <br />
                               
                                <div class="form-group">
                                    <input type="submit" class="btn btn-dark" value="Save" />
                                    <a asp-controller="Master_Accident" asp-action="Index" class="btn btn-outline-success">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

    <!-- END CONTENT BODY -->
</div>

<!-- END CONTENT -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>

        //dropdown for state
        function fnOnCountryChange() {

            var CountryID = $("#CountryID").val();

            if (CountryID !== "") {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByCountry","Master_Accident")" + "?&CountryID=" + CountryID,
                        data: {},
                        datatType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#StateID").append($("<option></option>").val(value.stateID).html(value.stateName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading Dropdown!");
                        }
                    }
                );
            }
            else {
                $("StateID").empty();
                $("StateID").append($("<option></option>").val("").html("Select State"));
            }
        }

        //drop down for city
        function fnOnStateChange() {

            var StateID = $("#StateID").val();

            if (StateID !== "") {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByState","Master_Accident")" + "?&StateID=" + StateID,
                        data: {},
                        datatType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#CityID").append($("<option></option>").val(value.cityID).html(value.cityName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading Dropdown!");
                        }
                    }
                );
            }
            else {
                $("CityID").empty();
                $("CityID").append($("<option></option>").val("").html("Select City"));
            }
        }
        

    </script>
}